import{readFileSync,lstatSync,realpathSync,writeFileSync,openSync,closeSync,fstatSync,constants}from'node:fs';
export function admitLifecycleRequest(value,sequence){
 if(!Number.isInteger(sequence)||sequence<1||sequence>4||value?.sequence!==sequence||Object.keys(value).sort().join(',')!=='action,sequence'||!['pause-server','resume-server'].includes(value.action)||value.action!==(sequence%2?'pause-server':'resume-server'))throw Error('closed sequential server lifecycle request required');
 return{sequence,action:value.action};
}
export class LifecycleMailbox{
 #directory;#identity;#next=1;#records=[];#busy=false;
 constructor(directory,{approvedRoot='/var/tmp/rom-010-authentik-20261007/run/volume/private'}={}){const root=realpathSync(approvedRoot),owner=lstatSync(root);if(root!==approvedRoot||!owner.isDirectory()||(owner.mode&0o777)!==0o700||owner.uid!==process.getuid()||!directory.startsWith(root+'/')||realpathSync(directory)!==directory)throw Error('owned lifecycle directory');const value=lstatSync(directory);if(!value.isDirectory()||(value.mode&0o777)!==0o700||value.uid!==process.getuid())throw Error('private lifecycle directory');this.#directory=directory;this.#identity=value;}
 async poll(provider,id){if(this.#busy)throw Error('lifecycle operation already pending');this.#busy=true;try{if(this.#next>4)return;const now=lstatSync(this.#directory);if(now.ino!==this.#identity.ino||now.dev!==this.#identity.dev)throw Error('lifecycle directory changed');const path=`${this.#directory}/request-${this.#next}.json`;let value;try{const file=lstatSync(path);if(!file.isFile()||file.nlink!==1||(file.mode&0o777)!==0o600||file.uid!==process.getuid()||file.size>1024)throw Error('private lifecycle request');const fd=openSync(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const opened=fstatSync(fd);if(opened.ino!==file.ino||opened.dev!==file.dev||opened.size!==file.size||opened.nlink!==1||(opened.mode&0o777)!==0o600)throw Error('lifecycle request changed');value=admitLifecycleRequest(JSON.parse(readFileSync(fd)),this.#next);}finally{closeSync(fd);}}catch(error){if(error.code==='ENOENT')return;throw error;}const observation=await provider[value.action==='pause-server'?'pause':'resume'](id);const record={...value,status:value.action==='pause-server'?'stopped':'freshly-admitted',observation,at_ms:Date.now()};writeFileSync(`${this.#directory}/response-${this.#next}.json`,JSON.stringify(record),{flag:'wx',mode:0o600});this.#records.push(record);this.#next++;}finally{this.#busy=false;}}
 records(){return [...this.#records];}
}
