import test from 'node:test';import assert from 'node:assert/strict';
import { NativeTlsCallbackHold, readNativeTlsBindingCookies } from './native-tls-callback-hold.mjs';
import { NativeTlsHandoff } from './native-tls-handoff.mjs';
const path='/rom-studio/auth/callback/authentik?code=original-code&state=original-state',cookie='rom_login=original-binding';
test('redirect destination callback is held before native forwarding and forwarded once only after arm',()=>{const hold=new NativeTlsCallbackHold();let forwarded=0;const dispatch=(target,armed)=>{const decision=hold.accept('GET',target,cookie,armed);if(decision.kind==='forward')forwarded++;return decision;};const result=dispatch(path,false);assert.equal(result.kind,'hold');assert.equal(forwarded,0);assert.equal(result.handoff.callback,'https://127.0.0.1:44389'+path);assert.equal(result.handoff.cookie,cookie);assert.equal(dispatch(path,true).kind,'forward');assert.equal(forwarded,1);assert.throws(()=>dispatch(path,true));});
test('duplicates and malformed route/query/cookie inputs never pass native forwarding',()=>{for(const [method,target,binding]of [['POST',path,cookie],['GET',path.replace('authentik?','%61uthentik?'),cookie],['GET',path.replace('authentik?','authentik/?'),cookie],['GET',path.replace('state=original-state','missing=x'),cookie],['GET',path+'&code=duplicate',cookie],['GET',path+'&state=duplicate',cookie],['GET',path,'rom_login=a; rom_login=b'],['GET',path,'other=b'],['GET',path+'x'.repeat(8192),cookie],['GET',path,'rom_login='+ 'x'.repeat(4097)]])assert.throws(()=>new NativeTlsCallbackHold().accept(method,target,binding,false));const h=new NativeTlsCallbackHold();h.accept('GET',path,cookie,false);assert.throws(()=>h.accept('GET',path,cookie,false));assert.throws(()=>h.accept('GET',path,cookie+'x',true));});
test('exact callback is distinct from ordinary host paths and cannot arm before capture plus browser drain',()=>{const h=new NativeTlsCallbackHold();assert.equal(h.accept('GET','/rom-studio/',cookie,false).kind,'forward');assert.throws(()=>h.accept('GET',path,cookie,true));const handoff=new NativeTlsHandoff('token');assert.throws(()=>handoff.arm());h.accept('GET',path,cookie,false);handoff.authorizationHeld();assert.throws(()=>handoff.arm());handoff.browserDrained();assert.equal(handoff.arm(),'rotate-before-callback');});

test('binding cookie lookup uses exact callback path without credential-bearing query', async()=>{const cookie={name:'rom_login',path:'/rom-studio/',secure:true,httpOnly:true,value:'original-binding'};let called;const context={cookies:async url=>{called=url;return new URL(url).pathname.startsWith(cookie.path)?[cookie]:[];}};const result=await readNativeTlsBindingCookies(context);assert.equal(called,'https://127.0.0.1:44389/rom-studio/auth/callback/authentik');assert.equal(new URL(called).search,'');assert.equal(new URL(called).hash,'');assert.deepEqual(result,[cookie]);assert.deepEqual(await context.cookies('https://127.0.0.1:44389'),[]);});
