import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync,writeFileSync,symlinkSync,unlinkSync,realpathSync}from'node:fs';import{tmpdir}from'node:os';import{inspectNativeTlsBrowserGraph,revalidateNativeTlsBrowserGraph}from'./native-tls-browser-graph.mjs';
const base=realpathSync(tmpdir())+'/';
function fixture(pnpm=false){const studio=mkdtempSync(base+'browser-graph-fixture-');writeFileSync(studio+'/package.json','{}');const packages=Object.fromEntries(['@playwright/test','playwright','playwright-core'].map(name=>['node_modules/'+name,{version:'1.63.0'}]));writeFileSync(studio+'/package-lock.json',JSON.stringify({packages}));const roots={};for(const name of ['@playwright/test','playwright','playwright-core']){const root=pnpm?studio+'/node_modules/.pnpm/'+name.replace('/','+')+'@1.63.0/node_modules/'+name:studio+'/node_modules/'+name;mkdirSync(root,{recursive:true});writeFileSync(root+'/package.json',JSON.stringify({name,version:'1.63.0'}));writeFileSync(root+'/index.js','export const version="1.63.0";');roots[name]=root;}if(pnpm){mkdirSync(studio+'/node_modules/@playwright',{recursive:true});symlinkSync('../.pnpm/@playwright+test@1.63.0/node_modules/@playwright/test',studio+'/node_modules/@playwright/test');symlinkSync(roots.playwright,roots['@playwright/test']+'/../../playwright');symlinkSync(roots['playwright-core'],roots.playwright+'/../playwright-core');}return{studio,roots};}
test('regular npm three-package graph is supported and revalidates',()=>{const f=fixture();const w=inspectNativeTlsBrowserGraph(f.studio);assert.equal(w.packages.length,3);assert.equal(w.aliases.every(a=>a.type==='directory'),true);assert.deepEqual(revalidateNativeTlsBrowserGraph(f.studio,w),w);});
test('explicit pnpm aliases resolve through real Node dependency semantics',()=>{const f=fixture(true);const w=inspectNativeTlsBrowserGraph(f.studio);assert.equal(w.aliases.length,3);assert.equal(w.aliases.every(a=>a.type==='symlink'),true);assert.equal(w.packages[2].root,f.roots['playwright-core']);assert.deepEqual(revalidateNativeTlsBrowserGraph(f.studio,w),w);});
test('package alias escape is rejected',()=>{const f=fixture(true),other=fixture();unlinkSync(f.studio+'/node_modules/@playwright/test');symlinkSync(other.roots['@playwright/test'],f.studio+'/node_modules/@playwright/test');assert.throws(()=>inspectNativeTlsBrowserGraph(f.studio),/escape/);});
test('wrong package version is rejected against admitted lock',()=>{const f=fixture();writeFileSync(f.roots.playwright+'/package.json',JSON.stringify({name:'playwright',version:'1.62.0'}));assert.throws(()=>inspectNativeTlsBrowserGraph(f.studio),/name\/version mismatch/);});
test('unexpected internal symlink is rejected rather than broadly followed',()=>{const f=fixture();symlinkSync('index.js',f.roots['playwright-core']+'/extra.js');assert.throws(()=>inspectNativeTlsBrowserGraph(f.studio),/internal browser symlink/);});
test('alias replacement fails revalidation even when canonical bytes are unchanged',()=>{const f=fixture(true),w=inspectNativeTlsBrowserGraph(f.studio),alias=f.studio+'/node_modules/@playwright/test';unlinkSync(alias);symlinkSync(f.roots['@playwright/test'],alias);assert.throws(()=>revalidateNativeTlsBrowserGraph(f.studio,w),/graph changed/);});
test('file mutation fails graph revalidation',()=>{const f=fixture(),w=inspectNativeTlsBrowserGraph(f.studio);writeFileSync(f.roots['playwright-core']+'/index.js','changed');assert.throws(()=>revalidateNativeTlsBrowserGraph(f.studio,w),/graph changed/);});
test('entry and byte bounds reject oversize graph',()=>{const f=fixture();assert.throws(()=>inspectNativeTlsBrowserGraph(f.studio,{maximumFiles:2}),/entry\/depth bound/);assert.throws(()=>inspectNativeTlsBrowserGraph(f.studio,{maximumBytes:1}),/byte bound/);});
