import test from 'node:test';import assert from 'node:assert/strict';import * as observers from './native-tls-stage-observer.mjs';
test('startup listener failure is distinct from an executable or trust guard failure',()=>{
 let now=0;const startup=new observers.NativeTlsStageObserver(()=>now);startup.enter('native-host-environment');startup.guard('trust-environment',true);startup.enter('native-host-listener');for(let i=0;i<40;i++){now+=100;startup.listenerAttempt();}startup.guard('listener',false);const a=startup.snapshot({name:'Error',message:'secret'});assert.equal(a.stage,'native-host-listener');assert.equal(a.role,'native-host');assert.equal(a.listener_attempts,40);assert.equal(a.stage_elapsed_ms,4000);assert.equal(a.guards.at(-1).category,'listener');
 const trust=new observers.NativeTlsStageObserver(()=>0);trust.enter('native-host-environment');trust.guard('trust-environment',false);const b=trust.snapshot({name:'Error'});assert.equal(b.stage,'native-host-environment');assert.equal(b.listener_attempts,0);assert.equal(b.guards.at(-1).category,'trust-environment');
});
test('native readiness and fixed stderr stages survive chunking without raw private data',()=>{
 const o=new observers.NativeTlsStageObserver(()=>0);o.enter('native-host-listener');o.consume('native-host','stdout',Buffer.from('{"status":"ready","lane":"native-tls-'));o.consume('native-host','stdout',Buffer.from('source-authoring","tls_verified":false}\n'));o.consume('native-host','stderr',Buffer.from('host_fixture_stage=seed\npassword=SECRET\n{"token":"SECRET"}\n'));const r=o.snapshot({name:'Error',message:'TOKEN',stack:'PASSWORD'});assert.equal(r.host_markers.ready,1);assert.equal(r.host_markers.stages.seed,1);assert.doesNotMatch(JSON.stringify(r),/SECRET|TOKEN|PASSWORD|password|token/);
});
test('unknown stages/roles and overflow are bounded and do not retain arbitrary text',()=>{
 const o=new observers.NativeTlsStageObserver(()=>0);assert.throws(()=>o.enter('secret-stage'));assert.throws(()=>o.consume('unknown','stdout',Buffer.from('x')));o.consume('native-host','stdout',Buffer.from('SECRET'.repeat(100000)));o.consume('native-host','stdout',Buffer.from('\n{"status":"ready","lane":"native-tls-source-authoring","tls_verified":false}\n'));const r=o.snapshot({name:'PrivateError'});assert.equal(r.error_name,'Other');assert.equal(r.output_overflow,true);assert.equal(r.host_markers.ready,1);assert.ok(Buffer.byteLength(JSON.stringify(r))<=8192);assert.doesNotMatch(JSON.stringify(r),/SECRET|PrivateError/);assert.throws(()=>o.guard('unknown',true));
});
