import test from 'node:test';
import assert from 'node:assert/strict';
import { validateNativeTlsOptions } from './native-tls-prepare.mjs';
const options = { adapter: 'sqlite', binary_identity: '/private/build.json', case_certificate: 'wrong-ca', case_route: 'token', client_input: '/private/client.json', native_ca: '/private/ca.pem', provider_ca: '/private/provider-ca.pem', negative_ca: '/private/negative-ca.pem', environment: '/private/provider.env', nss_reference: '/private/nss.json', provider_ready: '/private/ready.json', subject_input: '/private/subject.json', trusted_leaf: {}, negative_leaf: {} };
test('closed preparation rejects verification bypass and inherited arbitrary environment', () => {
  assert.equal(validateNativeTlsOptions(options).provider_backchannel, false);
  assert.throws(() => validateNativeTlsOptions({ ...options, env: process.env }));
  assert.throws(() => validateNativeTlsOptions({ ...options, ignore_https_errors: true }));
  assert.throws(() => validateNativeTlsOptions({ ...options, provider_backchannel: 'http://localhost' }));
});

// Tiny real DER certificates generated by Node crypto. No subprocess or listener.
import { generateKeyPairSync, sign, X509Certificate } from 'node:crypto';
import { validateNativeTlsMaterial } from './native-tls-prepare.mjs';
import { selectNativeTlsCase, nativeTlsCutoverRequired } from './native-tls-profile.mjs';
const der = (tag, ...parts) => {
  const body = Buffer.concat(parts), n = body.length;
  const length = n < 128 ? Buffer.from([n]) : n < 256 ? Buffer.from([0x81, n]) : Buffer.from([0x82, n >> 8, n & 255]);
  return Buffer.concat([Buffer.from([tag]), length, body]);
};
const seq = (...parts) => der(0x30, ...parts), oid = hex => der(0x06, Buffer.from(hex, 'hex'));
const algorithm = seq(oid('2a8648ce3d040302'));
const name = text => seq(der(0x31, seq(oid('550403'), der(0x0c, Buffer.from(text)))));
function testCertificate(key, subject, issuer, issuerKey, ca) {
  const extensions = [seq(oid('551d13'), der(0x01, Buffer.from([255])), der(0x04, ca ? seq(der(0x01, Buffer.from([255]))) : seq()))];
  if (!ca) extensions.push(seq(oid('551d11'), der(0x04, seq(der(0x87, Buffer.from([127, 0, 0, 1]))))));
  const tbs = seq(der(0xa0, der(0x02, Buffer.from([2]))), der(0x02, Buffer.from([1])), algorithm, name(issuer), seq(der(0x17, Buffer.from('250101000000Z')), der(0x17, Buffer.from('300101000000Z'))), name(subject), key.publicKey.export({ format: 'der', type: 'spki' }), der(0xa3, seq(...extensions)));
  return new X509Certificate(seq(tbs, algorithm, der(0x03, Buffer.from([0]), sign('sha256', tbs, issuerKey.privateKey))));
}
function material() {
  const a = generateKeyPairSync('ec', { namedCurve: 'prime256v1' }), b = generateKeyPairSync('ec', { namedCurve: 'prime256v1' }), leaf = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
  const providerCa = testCertificate(a, 'Provider root', 'Provider root', a, true), unrelatedCa = testCertificate(b, 'Unrelated root', 'Unrelated root', b, true);
  return { providerCa, unrelatedCa, trusted: testCertificate(leaf, 'Trusted loopback', 'Provider root', a, false), unrelatedLeaf: testCertificate(leaf, 'Unrelated loopback', 'Unrelated root', b, false) };
}

test('JWKS wrong issuer starts trusted, then accepts an unrelated valid leaf for cutover', () => {
  const m = material(), selected = selectNativeTlsCase({ route: 'jwks', certificate: 'wrong-ca', adapter: 'sqlite' });
  assert.doesNotThrow(() => validateNativeTlsMaterial(selected, { nativeCa: m.providerCa, providerCa: m.providerCa, negativeCa: m.unrelatedCa, trusted: m.trusted, negative: m.unrelatedLeaf }));
  assert.equal(nativeTlsCutoverRequired(selected), true);
  assert.throws(() => validateNativeTlsMaterial(selected, { nativeCa: m.unrelatedCa, providerCa: m.providerCa, trusted: m.trusted, negative: m.trusted }));
});

test('token wrong root stays unchanged and rejects a JWKS-style cutover construction', () => {
  const m = material(), selected = selectNativeTlsCase({ route: 'token', certificate: 'wrong-ca', adapter: 'sqlite' });
  assert.doesNotThrow(() => validateNativeTlsMaterial(selected, { nativeCa: m.unrelatedCa, providerCa: m.providerCa, trusted: m.trusted, negative: m.trusted }));
  assert.equal(nativeTlsCutoverRequired(selected), false);
  assert.throws(() => validateNativeTlsMaterial(selected, { nativeCa: m.providerCa, providerCa: m.providerCa, trusted: m.trusted, negative: m.unrelatedLeaf }));
});
