[package]
name = "rom-derive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
description = "Typed Resource framework rom-derive foundation"
repository.workspace = true
[lints]
workspace = true
[lib]
proc-macro = true
[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
