[package]
name = "resource-contract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
derive = ["dep:resource-contract-derive"]

[dependencies]
resource-contract-core = { path = "../core" }
resource-contract-derive = { path = "../derive", optional = true }
