import {chromium,webkit} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {parse,stringify} from 'lossless-json';
import {preflight} from './bounds.js';
const results=[],browsers=[];
async function run(name,fn){try{await fn();results.push({name,result:'pass'});}catch(error){results.push({name,result:'fail',error:error.message});}}
for(const [name,text] of [['integer','18446744073709551615'],['decimal','1.2300'],['exponent','1e+03']])await run('lossless '+name,()=>assert.equal(stringify(parse(text)),text));
await run('duplicate JSON keys rejected',()=>assert.throws(()=>parse('{"x":1,"x":2}')));
await run('null false zero empty remain distinct',()=>assert.equal(stringify(parse('[null,false,0,"",[],{}]')),'[null,false,0,"",[],{}]'));
await run('invalid JSON rejected',()=>assert.throws(()=>parse('{"x":}')));
await run('depth rejected before parser',()=>assert.throws(()=>preflight('['.repeat(7)+'0'+']'.repeat(7)),/depth/));
await run('UTF8 size rejected',()=>assert.throws(()=>preflight('"'+'🌎'.repeat(16384)+'"'),/size/));
await run('quoted brackets accepted',()=>{preflight('{"x":"[[[[[[[[[[[["}');parse('{"x":"[[[[[[[[[[[["}');});
for(const [engine,driver,path] of [['chromium',chromium,'/root/.nix-profile/bin/chromium'],['webkit',webkit,'/var/tmp/rom-studio-webkit-2359/pw_run.sh']]){
 let browser;try{browser=await driver.launch({executablePath:path,headless:true});}catch(error){results.push({name:engine+' launch',result:'blocked',error:error.message});continue;}
 browsers.push({engine,version:browser.version(),executable:path});
 const context=await browser.newContext({hasTouch:true,viewport:{width:900,height:700}});const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const reset=async(mode)=>{await page.goto('http://127.0.0.1:43323/');if(mode!=='Manual')await page.getByRole('button',{name:mode,exact:true}).click();await page.locator(mode==='Sortable'?'[data-row="b"] .handle':'[data-row="b"] input').waitFor();};
 const ids=async()=>JSON.parse(await page.getByTestId('values').textContent()).map(row=>row.id);
 for(const mode of ['Manual','Sortable'])await run(engine+' '+mode+' keyboard fallback identity error focus',async()=>{await reset(mode);await page.getByRole('button',{name:'Move b down',exact:true}).focus();await page.keyboard.press('Enter');assert.deepEqual(await ids(),['a','c','b']);assert.equal(await page.locator('[data-row="b"] input').inputValue(),'bad draft');assert.equal(await page.locator('[data-row="b"] .error').textContent(),'Invalid row b');await page.waitForFunction(()=>document.activeElement===document.querySelector('[data-row="b"] input'),undefined,{timeout:3000});assert.equal(await page.locator('[data-row="b"] input').evaluate(e=>e===document.activeElement),true);});
 await run(engine+' library keyboard handle reorder',async()=>{await reset('Sortable');await page.getByRole('button',{name:'Drag b',exact:true}).focus();await page.keyboard.press('Space');await page.keyboard.press('ArrowDown');await page.keyboard.press('Space');assert.deepEqual(await ids(),['a','c','b']);assert.equal(await page.locator('[data-row="b"] input').inputValue(),'bad draft');assert.equal(await page.locator('[data-row="b"] .error').textContent(),'Invalid row b');});
 await run(engine+' pointer handle reorder',async()=>{await reset('Sortable');const start=await page.getByRole('button',{name:'Drag b',exact:true}).boundingBox(),end=await page.locator('[data-row="c"]').boundingBox();await page.mouse.move(start.x+start.width/2,start.y+start.height/2);await page.mouse.down();await page.mouse.move(end.x+start.width/2,end.y+end.height-5,{steps:20});await page.waitForTimeout(400);await page.mouse.up();await page.waitForTimeout(400);assert.deepEqual(await ids(),['a','c','b']);assert.equal(await page.locator('[data-row="b"] input').inputValue(),'bad draft');});
 if(engine==='chromium')await run(engine+' synthetic touch handle reorder',async()=>{await reset('Sortable');await page.locator('[data-row="b"] .handle').evaluate(async e=>{const rect=e.getBoundingClientRect(),end=document.querySelector('[data-row="c"]').getBoundingClientRect();let x=rect.x+rect.width/2,y=rect.y+rect.height/2;const fire=(type,target,x,y)=>{let touch=new Touch({identifier:1,target:e,clientX:x,clientY:y,pageX:x+scrollX,pageY:y+scrollY});target.dispatchEvent(new TouchEvent(type,{bubbles:true,cancelable:true,touches:type==='touchend'?[]:[touch],targetTouches:type==='touchend'?[]:[touch],changedTouches:[touch]}));};fire('touchstart',e,x,y);await new Promise(r=>setTimeout(r,150));fire('touchmove',window,x,end.y+end.height-5);await new Promise(r=>setTimeout(r,500));fire('touchend',window,x,end.y+end.height-5);});await page.waitForTimeout(500);assert.deepEqual(await ids(),['a','c','b']);});
 if(engine==='webkit')results.push({name:'webkit touch drag',result:'not executed',reason:'Touch constructor unavailable; physical-device touch not claimed'});
 if(engine==='chromium')await run(engine+' CDP touch handle reorder',async()=>{await reset('Sortable');const a=await page.locator('[data-row="b"] .handle').boundingBox(),z=await page.locator('[data-row="c"]').boundingBox(),session=await context.newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2}]});await page.waitForTimeout(150);for(let i=1;i<=12;i++){await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2+(z.y+z.height-5-a.y-a.height/2)*i/12}]});await page.waitForTimeout(35);}await page.waitForTimeout(300);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(400);assert.deepEqual(await ids(),['a','c','b']);await session.detach();});
 await run(engine+' nested input does not drag',async()=>{await reset('Sortable');await page.locator('[data-row="b"] input').fill('new invalid');assert.deepEqual(await ids(),['a','b','c']);});
 await run(engine+' active keyboard teardown remount',async()=>{await reset('Sortable');await page.getByRole('button',{name:'Drag b',exact:true}).focus();await page.keyboard.press('Space');await page.getByRole('button',{name:'Toggle editor'}).click();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Toggle editor'}).click();await page.getByRole('button',{name:'Move b down',exact:true}).click();assert.deepEqual(await ids(),['a','c','b']);assert.equal(await page.locator('#dnd-action-dragged-el').count(),0);});
 await run(engine+' document exact tokens and escaped HTML',async()=>{await page.goto('http://127.0.0.1:43323/');await page.getByRole('button',{name:'Document',exact:true}).click();await page.getByRole('button',{name:'Apply document'}).waitFor();await page.getByRole('button',{name:'Apply document'}).click();const text=await page.getByTestId('accepted').textContent();assert.match(text,/18446744073709551615/);assert.match(text,/1\.2300/);assert.match(text,/1e\+03/);assert.equal(await page.locator('img').count(),0);});
 await run(engine+' document tree text token roundtrip',async()=>{await page.getByRole('button',{name:'Tree mode'}).click();await page.waitForTimeout(150);await page.getByRole('button',{name:'Text mode'}).click();await page.waitForTimeout(150);await page.getByRole('button',{name:'Apply document'}).click();const text=await page.getByTestId('accepted').textContent();assert.match(text,/18446744073709551615/);assert.match(text,/1\.2300/);assert.match(text,/1e\+03/);});
 await run(engine+' document invalid draft blocked',async()=>{await page.locator('.cm-content').click();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('{"x":}');await page.waitForTimeout(300);await page.getByRole('button',{name:'Apply document'}).click();assert.ok((await page.getByRole('alert').textContent()).length>0);});
 await run(engine+' exact textarea keeps document and blocks invalid size depth',async()=>{await page.getByRole('button',{name:'Exact textarea',exact:true}).click();await page.locator('#exact-document').waitFor();await page.getByRole('button',{name:'Apply document'}).click();let accepted=await page.getByTestId('accepted').textContent();assert.match(accepted,/18446744073709551615/);assert.match(accepted,/1\.2300/);for(const [text,pattern]of [['{',/./],['['.repeat(7)+'0'+']'.repeat(7),/depth/],[' '+ '0'.repeat(65537),/size/]]){await page.locator('#exact-document').fill(text);await page.getByRole('button',{name:'Apply document'}).click();assert.match(await page.getByRole('alert').textContent(),pattern);assert.equal(await page.getByTestId('accepted').textContent(),accepted);}});
 await run(engine+' runtime no page errors',()=>assert.deepEqual(errors,[]));await browser.close();
}
writeFileSync('results.json',JSON.stringify({date:new Date().toISOString(),node:process.version,browsers,results},null,2));console.log(JSON.stringify(results,null,2));if(results.some(r=>r.result==='fail'))process.exitCode=1;
