[package]
name = "rom-storage-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
[lints]
workspace = true
[dev-dependencies]
rom-conformance.workspace = true
rom-backup = {version="=0.1.0-alpha.1",path="../../crates/rom-backup"}
rom.workspace = true
rom-sqlite = { workspace = true, features = ["test-support"] }
rom-redb = { workspace = true, features = ["test-support"] }
redb.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
tokio.workspace = true
