[package]
name = "rom-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
description = "Typed Resource framework rom-sqlite foundation"
repository.workspace = true
[lints]
workspace = true
[dependencies]
rom-backup = {version="=0.0.3",path="../rom-backup"}
rom.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
url = { version = "=2.5.8", default-features = false, features = ["std"] }
[features]
test-support = []
